# 所有对话信息

level_chats = (((1, "Hello there new challenger!"),
               (1, "Welcome to Snake Quest, where you will face multiple challenges!"),
               (2, "What's the prize?"),
               (1, "The prize is endless food!"),
               (2, "yeye how do I start"),
               (1, "But first I need to go through the controls with ya"),
               (1, "The snake will follow your cursor"),
               (1, "Going outside of the boundary will kill you"),
               (1, "When your hp drops to 0, you are basically dead"),
               (1, "On the top left corner, is your current level. The higher the level the longer the snake"),
               (1, "In the first stage, you only need to reach level 3"),
               (2, "ezpz"),
               (1, "You will regret saying that :^)"),
               (1, "Finish this dialog whenever you are ready!")),

               ((1, "Congrats on finishing stage one!"),
                (1, "The real challenge begins now"),
                (2, "git gud too ez"),
                (1, "In stage two you will need to dodge cannonballs."),
                (1, "Similarly, walking outside of the boundary will kill you."),
                (2, "that's it?"),
                (1, "yep that's it"),
                (1, "But you will need to reach level 5 this time."),
                (1, "Finish this dialog whenever you are ready!")),

               ((1, "Looks like you are adapting to this."),
                (1, "Here comes level 3."),
                (2, "What's in level 3?"),
                (1, "Lasers, four of them"),
                (1, "It will be right in the middle, get ready to dodge"),
                (1, "You gotta dodge them!"),
                (2, "well that's all?"),
                (1, "Not only that! In this stage each food gives double the xp"),
                (1, "You will also need to reach level 10"),
                (1, "In other words, you will grow longer"),
                (2, "gotcha, I'm ready"),
                (1, "Finish this dialog whenever you are ready!")),

               ((1, "Stage 4, is the hardest of them all in my opinion"),
                (2, "yeyeye?"),
                (1, "Do you remember the lazers?"),
                (2, "Too ez with my dodging skills"),
                (1, "But in this stage the lazers move as well~"),
                (2, "?say what"),
                (1, "Finish this dialog whenever you are ready!")),

               ((1, "We are starting stage 5!"),
                (2, "Stage 4 was too ez, twas not hard at all"),
                (1, "In that case, stage 5 will be even easier!"),
                (1, "There's only one trick: run in circles"),
                (2, "What does that mean?"),
                (1, "You will see~"),
                (1, "Hint: try not to stay in the middle after the first 2 seconds"),
                (2, "I should stay at the edges?"),
                (1, "Exactly~Finish this dialog whenever you are ready!")),

               ((1, "Congrats on finishing level 5!"),
                (2, "<_< that first laser scared me a lil"),
                (1, "lol I will make stage 6 clearer"),
                (2, "you'd better be <_<"),
                (1, "you'll still get the laser, but an ultra large one!"),
                (1, "It's so big that it covers half of the field!"),
                (2, "but, how am I supposed to dodge that?"),
                (1, "It's also so large that it needs a long time to recharge"),
                (1, "Just dodge it while it's charging!"),
                (2, "gocha"),
                (1, "GL, end this dialog whenever you are ready!")),

               ((1, "Welcome to the last stage!"),
                (2, "Finally!"),
                (1, "It was a long way here! So I made this level easier."),
                (2, "yeyeye?"),
                (1, "You will need to reach level 15, and dodge a few things"),
                (2, "ye?"),
                (1, "GL, end this dialog whenever you are ready!")),

               ((1, "Congrats! You finished the whole game!"),
                (2, "Yea!!"),
                (1, "Now you have gained access to infinite amount of food!"),
                (2, "yayay :DDDD"),
                (1, "Thank you for playing!"),
                (2, "It's a small game made with pygame by Jeff Yan"),
                (2, "Thank you very much for playing!"),
                (1, "Thank you!!!"))
               )
